version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'hits'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
  backend:
    build: 
      context: ./Python
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: 'hits'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_HOST: 'db'
  frontend:
    image: nginx:1.21.0-alpine
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
